### ISSUE TITLE
Concrete implementation of ITextLayouter 

### ISSUE THREAD

**Issue by menjaraz** [a-ludi/printed-text#4]
Where can be found a _concrete implementation_ of ITextLayouter ?

**Comment by a-ludi** [comment]
Hi @menjaraz ,

I am sorry but there is no implementation available. I have some code on my machine but the code is not in any state to be published.

I do not find the time to work on this anymore, so feel free to build on my work. I will make the code of my initial attempt available if you like.

Cheers,

Arne
